# Generated by Django 3.2 on 2021-04-17 11:54

from django.db import migrations, models
import django.db.models.deletion

def add_products(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Product = apps.get_model("ecommerce_app", "Product")
    Product.objects.create(id=1, name="TShirt", price=1000, category="clothes", slug="item1", description="Testing",)
    Product.objects.create(id=2, name="Shorts", price=1500, category= "clothes", slug="item2", description="Testing",recommended= Product.objects.get(name="TShirt"))
    Product.objects.create(id=3, name="Notebook", price=400,category = "stationary", slug="item3", description="Testing",)
    Product.objects.create(id=4, name="Pen", price=50, category = "stationary", slug="item4", description="Testing", recommended =  Product.objects.get(name="Notebook"))
    Product.objects.get(name ="TShirt").recommended = Product.objects.get(name="Shorts")
    Product.objects.get(name ="Notebook").recommended = Product.objects.get(name="Pen")




class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', models.IntegerField()),
                ('address', models.CharField(max_length=191)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('clicks', models.IntegerField(default=0)),
                ('recommended', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce_app.product')),
            ],
        ),
        migrations.RunPython(add_products),
    ]
