# Generated by Django 3.2 on 2021-04-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_alter_product_recommended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
